/**
 * Generates supabase/seed.sql from src/data/projects.ts.
 * Run with: npx tsx supabase/generate-seed.ts
 *
 * Re-run whenever src/data/projects.ts changes until the seed table moves
 * fully into the database.
 */
import { writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { PROJECTS } from '../src/data/projects';

function sqlString(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

function sqlArray(items: string[]): string {
  if (items.length === 0) return `'{}'`;
  const inner = items.map((s) => `"${s.replace(/"/g, '\\"')}"`).join(',');
  return `'{${inner}}'`;
}

function sqlNullableString(value: string | undefined | null): string {
  return value == null ? 'null' : sqlString(value);
}

const lines: string[] = [];
lines.push('-- Generated by supabase/generate-seed.ts — do not edit by hand.');
lines.push('-- Regenerate with: npx tsx supabase/generate-seed.ts');
lines.push('');
lines.push('begin;');
lines.push('');
lines.push('-- Wipe + reseed (idempotent).');
lines.push('delete from public.units;');
lines.push('delete from public.projects;');
lines.push('');
lines.push(
  'insert into public.projects (id, name, developer, city, district, status, class_type, building_type, buildings, total_units, size_min, size_max, floors, price_per_sqm, min_price, completion, amenities, dist_sea, lat, lng, date_added, data_confidence, description) values',
);

const projectRows = PROJECTS.map((p) => {
  return `  (${p.id}, ${sqlString(p.name)}, ${sqlString(p.developer)}, ${sqlString(p.city)}, ${sqlString(p.district)}, ${sqlString(p.status)}, ${sqlString(p.classType)}, ${sqlString(p.buildingType)}, ${p.buildings}, ${p.totalUnits}, ${p.sizeMin}, ${p.sizeMax}, ${p.floors}, ${p.pricePerSqm}, ${p.minPrice}, ${sqlString(p.completion)}, ${sqlArray(p.amenities)}, ${p.distSea}, ${p.lat}, ${p.lng}, ${sqlNullableString(p.dateAdded)}, ${sqlNullableString(p.dataConfidence)}, ${sqlNullableString(p.description)})`;
});
lines.push(projectRows.join(',\n') + ';');
lines.push('');

const unitRows: string[] = [];
for (const p of PROJECTS) {
  for (const u of p.units) {
    unitRows.push(
      `  (${p.id}, ${sqlString(u.id)}, ${sqlString(u.building)}, ${u.floor}, ${u.rooms}, ${u.area}, ${u.price}, ${sqlString(u.status)})`,
    );
  }
}

if (unitRows.length > 0) {
  lines.push(
    'insert into public.units (project_id, id, building, floor, rooms, area, price, status) values',
  );
  lines.push(unitRows.join(',\n') + ';');
  lines.push('');
}

lines.push('commit;');
lines.push('');

const here = dirname(fileURLToPath(import.meta.url));
const outPath = join(here, 'seed.sql');
writeFileSync(outPath, lines.join('\n'), 'utf8');

console.log(
  `Wrote ${outPath} — ${PROJECTS.length} projects, ${unitRows.length} units.`,
);
